In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.2


In [3]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
None


In [13]:
arr1=np.zeros((10))
arr2=np.array([4,3])

In [14]:
#Size of an array
arr2.size

2

In [16]:
# memory size of an array of one array element in byte
arr2.itemsize

4

In [17]:
# memory size of an numpy array in byte
arr2.size * arr2.itemsize

8

In [18]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [19]:
arr1=np.zeros(10)

In [21]:
arr1[5]=1

In [22]:
arr1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [23]:
arr1=np.arange(10,49,1)

In [24]:
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [29]:
arr1= np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [31]:
arr2=arr1[::-1] # one way of reversing array
arr2
arr3=np.flip(arr1,axis=None)

In [32]:
arr3

array([5, 4, 3, 2, 1])

In [35]:
arr3=np.array?

In [38]:
arr3=np.arange(0,9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
arr3=np.array([1,2,0,0,4,0])

In [40]:
arr3

array([1, 2, 0, 0, 4, 0])

In [43]:
np.nonzero(arr3) # return indices of non zero elements

(array([0, 1, 4], dtype=int64),)

In [46]:
arr3=np.eye(3,3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
arr3=np.random.randn(3,3,3)
arr3

array([[[-0.64643947,  0.36985617,  0.13160103],
        [ 0.03227192,  0.41829621,  0.56892556],
        [ 0.89523012, -0.87956891,  1.07839536]],

       [[-0.29850329, -1.18227667,  0.75222632],
        [ 0.53447832, -1.18780621, -0.4222841 ],
        [ 0.81229865,  0.59490824, -0.91097628]],

       [[-0.0181909 ,  0.6867571 ,  1.07411961],
        [-0.07274018,  1.07674272, -0.64812136],
        [ 0.48101061, -0.76615708, -1.88297541]]])

In [50]:
arr3=np.random.randn(10,10)

In [51]:
arr3

array([[ 0.73981292,  0.41367615, -0.35308299,  0.02750489, -0.20921317,
        -2.57626132, -0.09411743, -0.71744723, -0.15436484,  0.30734269],
       [ 0.40380727,  1.56772944, -0.41298523, -0.33828186,  0.42491031,
        -0.07155334,  0.55737777, -0.03876367, -1.02542722, -0.34363009],
       [-0.33199058,  0.76161094, -0.09659082, -0.56400196,  2.98253957,
         0.40324   , -1.37392865, -0.42100243,  0.12962609,  0.47299531],
       [ 0.31789983, -0.06522902, -1.29703939,  0.95552966,  0.59630707,
         0.37327515, -1.06661922,  0.25855925, -0.0064822 ,  0.65458656],
       [ 1.49699367, -0.07999254,  0.35944756, -2.27986006,  0.4930142 ,
        -0.30157223, -0.67221839,  2.64128126,  0.94232291,  0.75581865],
       [ 0.33460478, -1.27149757, -1.0284495 ,  0.5695246 ,  1.29304502,
         1.85197925, -1.85136223,  0.78407925,  0.42194095, -0.69590498],
       [-1.01789406, -1.22074817,  0.34740058, -0.15913121, -2.13852902,
        -0.43969098,  2.53856655, -0.01608962

In [52]:
arr3.min()

-2.576261320355879

In [54]:
arr3.max()

2.982539565144754

In [57]:
arr3=np.random.randn(30)

In [58]:
arr3

array([ 0.78036378, -1.00991165, -1.58689357,  0.91679281,  0.84093694,
        0.37586615,  0.31453032, -0.55152301, -1.31791329,  0.56939324,
        0.71889335,  0.27091996, -0.62832975, -1.37970514, -1.87434274,
       -1.39662162,  0.66296276, -0.14579585, -0.2417543 , -0.60347551,
       -0.22372379,  1.59052937, -1.91923853, -1.97419136,  0.0322373 ,
        0.32735735, -0.22279148, -1.21265611, -1.0041408 , -1.9421117 ])

In [59]:
arr3.mean()

-0.3944778947462327

In [63]:
arr3=np.ones((2,2))
arr3

array([[1., 1.],
       [1., 1.]])

In [64]:
arr3=np.random.randn(3,3)

In [65]:
arr3

array([[-7.41695988e-04,  3.34816071e-01, -3.40591614e-01],
       [ 3.06999788e-01, -1.07629823e+00,  6.53718082e-01],
       [-9.16510791e-02,  9.62995625e-01,  4.67893534e-01]])

In [68]:
arr3[0]=[0,0,0]
arr3[2]=[0,0,0]

In [69]:
arr3

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.30699979, -1.07629823,  0.65371808],
       [ 0.        ,  0.        ,  0.        ]])

In [72]:
arr3[1,0:1]=0
arr3[1,2:]=0

In [73]:
arr3

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        , -1.07629823,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [74]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [87]:
arr3=np.random.randn(5,5)

In [88]:
arr3

array([[-1.25930535,  1.04971862,  0.30423931, -0.32484089,  0.84201979],
       [-1.29742654,  0.53164552, -0.60816515,  0.98359623, -0.23327014],
       [ 0.0263635 ,  0.92707425, -1.03859039, -1.00884139, -0.49449645],
       [-0.68320785,  2.14974535,  1.25452595, -0.52115695,  0.62991852],
       [ 0.18575052,  0.01468263, -0.077728  ,  0.99593846, -1.28856799]])

In [98]:

for i in range(1,5):
    arr3[i:,i-1]=i
    

In [99]:
arr3

array([[-1.25930535,  1.04971862,  0.30423931, -0.32484089,  0.84201979],
       [ 1.        ,  0.53164552, -0.60816515,  0.98359623, -0.23327014],
       [ 1.        ,  2.        , -1.03859039, -1.00884139, -0.49449645],
       [ 1.        ,  2.        ,  3.        , -0.52115695,  0.62991852],
       [ 1.        ,  2.        ,  3.        ,  4.        , -1.28856799]])

In [117]:
arr3=np.random.randn(5,5)
print(arr3)
j=0
for i in range(1,5):
    print(i)
    print(j)
    arr3[i,j]=i
    j+=1

[[ 0.0353969  -0.66720785  0.79705697 -1.52555419  0.7758748 ]
 [ 0.82461586  0.80346224 -1.28346178 -0.4997178   1.61591905]
 [-0.78017919 -0.63194484  2.34890586  0.7540184  -0.98695368]
 [ 0.16162006 -0.05422343  1.56131132 -0.04412803  0.059172  ]
 [ 0.42255654 -0.058448   -0.02787572  2.41518542  0.65506912]]
1
0
2
1
3
2
4
3


In [118]:
arr3

array([[ 0.0353969 , -0.66720785,  0.79705697, -1.52555419,  0.7758748 ],
       [ 1.        ,  0.80346224, -1.28346178, -0.4997178 ,  1.61591905],
       [-0.78017919,  2.        ,  2.34890586,  0.7540184 , -0.98695368],
       [ 0.16162006, -0.05422343,  3.        , -0.04412803,  0.059172  ],
       [ 0.42255654, -0.058448  , -0.02787572,  4.        ,  0.65506912]])

In [146]:
arr3=np.zeros((8,8))

In [148]:
arr3

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [152]:
for i in range(0,8):
    print(i)
    for j in range(0,8):
        if (i==0 or i%2==0) and (j==0 or j%2==0):
            arr3[i,j]=1
arr3

0
1
2
3
4
5
6
7


array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [162]:
arrr4=np.ones((6,7,8))

In [164]:
arrr4

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.,

array([1., 0., 1., 0., 1., 0., 1., 0.])